server {
  listen 80;
  root /usr/share/nginx/html;
  location / {
    try_files $uri $uri/ /index.html;
  }
  location /api/ {
    client_max_body_size 10m;
    proxy_pass http://api:8080/api/;
    proxy_set_header Host $host;
  }
}
