DROP TABLE IF EXISTS order_return_items;
DROP TABLE IF EXISTS order_returns;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS carts;
